services:
  postgres_db:
    image: postgres:16-alpine
    container_name: undp_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-undp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-undp_password}
      POSTGRES_DB: ${POSTGRES_DB:-undp_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: undp_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@undp.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-adminpassword}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres_db

volumes:
  postgres_data: